69 implement cloud init intergration
Cloud-Temple/terraform-provider-cloudtemple pull request #70
Opened 2023-07-28 15:35 UTC by pbesret

**What changed :**
- Implemented cloud-init integration for OVF deployement from the content library.
- Added exemple usage for cloud-init.

2023-08-09 16:25 UTC, aureldsn requested changes

2023-08-09 16:25 UTC, aureldsn commented on internal/provider/resource_compute_virtual_machine.go
> +				},
This validation doesn't work, see: https://developer.hashicorp.com/terraform/plugin/sdkv2/schemas/schema-types#typemap

A quick workaround:

```suggestion
				Elem: &schema.Schema{
					Type:         schema.TypeString,
				},
				ValidateDiagFunc: validation.MapKeyMatch(regexp.MustCompile(strings.Join([]string{
					"^user-data$",
					"^network-config$",
					"^public-keys$",
					"^instance-id$",
					"^password$",
					"^hostname$",
					"^seedfrom$"},
					"|")), ""),
```

2023-08-09 16:25 UTC, aureldsn commented on internal/provider/resource_compute_virtual_machine.go
> +	- ` + "`network-config` (This value value should be base64 encoded)" + `
the word `value` is duplicated

```suggestion
	- ` + "`user-data` (This value should be base64 encoded)" + `
	- ` + "`network-config` (This value should be base64 encoded)" + `
```

2023-08-09 16:25 UTC, aureldsn commented on docs/resources/compute_virtual_machine.md
> +	- `network-config` (This value value should be base64 encoded)
the word `value` is duplicated

```suggestion
	- `user-data` (This value should be base64 encoded)
	- `network-config` (This value should be base64 encoded)
```

2023-08-21 10:36 UTC, aureldsn approved these changes

2023-08-21 12:16 UTC, KChapron approved these changes

2023-08-21 12:16 UTC, merged